### ISSUE TITLE
Fives

### ISSUE THREAD

**Issue by munderseth** [s2testorg/sessionCycles#4]
```
Capture the **Fives** only specs. 
testspace:
  branch: simple.cycles
  specs: 
    path: cycle3
    ignore:
      - *.md
      - five!
```
