### ISSUE TITLE
Fives

### ISSUE THREAD

**Issue by munderseth** [s2testorg/sessionCycles#5]
Capture the **Fives** only specs. 
```
testspace:
  branch: simple.cycles
  specs: 
    path: cycle3
    ignore:
      - "**/*.md"
      - "!five*"
```
